version: '2'
services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongo

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  frame_concentrator:
    build: ./FrameConcentrator
    image: frame-concentrator
    links:
      - mongo
      - rabbitmq
    environment:
      - "FEATURES=haarcascade_frontalface_default:haarcascade_frontalface_alt:haarcascade_frontalface_alt2:haarcascade_fullbody:haarcascade_upperbody:haarcascade_profileface"
      - "VCAP_SERVICES={\"compose-for-rabbitmq\": [{\"credentials\": {\"uri\": \"amqp://rabbitmq:5672\"}}], \"compose-for-mongodb\": [{\"credentials\": {\"uri\": \"mongodb://mongo:27017\"}}]}"

  haarcascade_frontalface_default:
    extends:
      file: common-services.yml
      service: haarcascade
    links:
      - rabbitmq
    environment:
      - "HAAR_CASCADE=haarcascade_frontalface_default"
      - "VCAP_SERVICES={\"compose-for-rabbitmq\": [{\"credentials\": {\"uri\": \"amqp://rabbitmq:5672\"}}]}"
    depends_on:
      - frame_concentrator

  haarcascade_frontalface_alt:
    extends:
      file: common-services.yml
      service: haarcascade
    links:
      - rabbitmq
    environment:
      - "HAAR_CASCADE=haarcascade_frontalface_alt"
      - "VCAP_SERVICES={\"compose-for-rabbitmq\": [{\"credentials\": {\"uri\": \"amqp://rabbitmq:5672\"}}]}"
    depends_on:
      - frame_concentrator

  haarcascade_frontalface_alt2:
    extends:
      file: common-services.yml
      service: haarcascade
    links:
      - rabbitmq
    environment:
      - "HAAR_CASCADE=haarcascade_frontalface_alt2"
      - "VCAP_SERVICES={\"compose-for-rabbitmq\": [{\"credentials\": {\"uri\": \"amqp://rabbitmq:5672\"}}]}"
    depends_on:
      - frame_concentrator

  haarcascade_fullbody:
    extends:
      file: common-services.yml
      service: haarcascade
    links:
      - rabbitmq
    environment:
      - "HAAR_CASCADE=haarcascade_fullbody"
      - "VCAP_SERVICES={\"compose-for-rabbitmq\": [{\"credentials\": {\"uri\": \"amqp://rabbitmq:5672\"}}]}"
    depends_on:
      - frame_concentrator

  haarcascade_upperbody:
    extends:
      file: common-services.yml
      service: haarcascade
    links:
      - rabbitmq
    environment:
      - "HAAR_CASCADE=haarcascade_upperbody"
      - "VCAP_SERVICES={\"compose-for-rabbitmq\": [{\"credentials\": {\"uri\": \"amqp://rabbitmq:5672\"}}]}"
    depends_on:
      - frame_concentrator

  haarcascade_profileface:
    extends:
      file: common-services.yml
      service: haarcascade
    links:
      - rabbitmq
    environment:
      - "HAAR_CASCADE=haarcascade_profileface"
      - "VCAP_SERVICES={\"compose-for-rabbitmq\": [{\"credentials\": {\"uri\": \"amqp://rabbitmq:5672\"}}]}"
    depends_on:
      - frame_concentrator

  cnn_processor:
    build: ./CnnProcessor
    image: cnn-processor
    links:
      - rabbitmq
    environment:
      - "VCAP_SERVICES={\"compose-for-rabbitmq\": [{\"credentials\": {\"uri\": \"amqp://rabbitmq:5672\"}}]}"
    depends_on:
      - frame_concentrator
      - haarcascade_frontalface_default
      - haarcascade_frontalface_alt
      - haarcascade_frontalface_alt2
      - haarcascade_fullbody
      - haarcascade_upperbody
      - haarcascade_profileface

  attendance_aggregator:
    build: ./AttendanceAggregator
    image: attendance-aggregator
    links:
      - rabbitmq
    environment:
      - "VCAP_SERVICES={\"compose-for-rabbitmq\": [{\"credentials\": {\"uri\": \"amqp://rabbitmq:5672\"}}]}"
    depends_on:
      - frame_concentrator
      - cnn_processor

  train_data_recorder:
    build: ./TrainDataRecorder
    image: train-data-recorder
    links:
      - rabbitmq
    environment:
      - "VCAP_SERVICES={\"compose-for-rabbitmq\": [{\"credentials\": {\"uri\": \"amqp://rabbitmq:5672\"}}]}"
    depends_on:
      - frame_concentrator
