version: '2'
services:
  mongo:
    image: registry.eu-gb.bluemix.net/clodes3/mongo
    ports:
    - "27017:27017"
  mongo_express:
    image: registry.eu-gb.bluemix.net/clodes3/mongo-express
    ports:
    - "8081:8081"
    links:
    - mongo
    depends_on:
    - mongo

  rabbitmq_management:
    image: registry.eu-gb.bluemix.net/clodes3/rabbitmq:management
    ports:
    - "15672:15672"
    - "5672:5672"
