version: '2'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  mongo_express:
    image: mongo-express
    ports:
    - "8081:8081"
    links:
    - mongo
    depends_on:
    - mongo

  rabbitmq_management:
    image: rabbitmq:management
    ports:
    - "15672:15672"
    - "5672:5672"
